version: "3.7"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: agrotech
      POSTGRES_PASSWORD: Bxm6*7lW6MSY
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql
      - .:/var/lib/postgresql/data
    ports:
      - "8432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U agrotech -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped